### ISSUE TITLE
Why strip scheme?

### ISSUE THREAD

**Issue by helpermethod** [sindresorhus/filenamify-url#1]
Hi,

maybe a stupid question but what is the motivation for stripping away the scheme? Wouldn't keeping the scheme allow more url normalizations?

Thank you!

**Comment by sindresorhus** [comment]
> maybe a stupid question but what is the motivation for stripping away the scheme?

To simplify the filename. It's not essential to the filename whether it came from HTTP or HTTPS.

> Wouldn't keeping the scheme allow more url normalizations?

Not sure what you're asking here?

**Comment by helpermethod** [comment]
Thank you, I guess I was overthinking things.
