### ISSUE TITLE
Ability to reconstruct URL from filename

### ISSUE THREAD

**Issue by foolip** [sindresorhus/filenamify-url#2]
I have a list of test names (in reports from https://github.com/web-platform-tests/) which are of the form `/encoding/legacy-mb-japanese/iso-2022-jp/iso2022jp-decode.html?5001-6000` or `/xhr/xmlhttprequest-timeout-worker-synconworker.html?load fires normally`, to give two examples.

I'd like write a file per test on the filesystem, and came to this repo and https://github.com/sindresorhus/filenamify for a solution.

However, I have an additional requirement of being able to reconstruct the original string byte-for-byte, so I need to be able to reverse the escaping.

In either project, a `unfilenamify` or `unfilenamifyUrl` that is guaranteed to return the original string would be great.

**Comment by sindresorhus** [comment]
This module is not a good fit for your use-case as the escaping isn't easily reversible. Your use-case would be much better solved by just base64 encoding the filename.
